[package]
name = "roku-cmd"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
roku-api-gateway = { path = "../roku-api-gateway" }
roku-common-types = { path = "../roku-common-types" }
roku-runtime-service = { path = "../roku-runtime-service" }
