[package]
name = "roku-api-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
actix-web = "4"
async-trait = "0.1"
roku-common-types = { path = "../roku-common-types" }
roku-runtime-service = { path = "../roku-runtime-service" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
